name: smart_therapy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  model_viewer_plus: ^1.3.3
  firebase_core: ^2.4.1
  google_fonts:
  intl: ^0.18.1
  get: ^4.6.5
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.4.3
  webview_flutter: ^3.0.4
  camera: ^0.10.3+2
  tflite: ^1.1.2
  text_to_speech:
  flutter_stripe: ^9.5.0+1
  photo_view: ^0.14.0
  url_launcher: ^6.1.10
  dashed_circular_progress_bar:
  typicons_flutter: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/disorders/
    - assets/3d_models/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
